name: Node.js Publish Release

on:
  release:
    types: [released]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      # Eventually this will be a loop over all packages
      - run: cd packages/block && pnpm run build
      - run: cd packages/block && echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
      - run: cd packages/block && npm publish --access public
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
